# Generated by Django 4.2.5 on 2023-09-21 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def adicionar_operacoes(apps, schema_editor):
    Operacao = apps.get_model("banco", "Operacao")
    db_alias = schema_editor.connection.alias
    Operacao.objects.using(db_alias).bulk_create(
        [
            Operacao(descricao="Depósito"),
            Operacao(descricao="Levantamento"),
        ]
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('conta_id', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contas',
                'db_table': 'contas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('operacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Operacoes',
                'db_table': 'operacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('morada', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Perfis',
                'db_table': 'perfis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('movimentacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('montante', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.conta')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.operacao')),
            ],
            options={
                'verbose_name_plural': 'Movimentacoes',
                'db_table': 'movimentacoes',
                'managed': True,
            },
        ),
        migrations.RunPython(adicionar_operacoes),
    ]
